opendistro-for-elasticsearch/anomaly-detection

- src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
Change AD setting name to keep align with other ODFE plugins.
> change AD setting name

- src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestDeleteAnomalyDetectorAction.java
- src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
- src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/HashRingTests.java
- src/test/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndicesTests.java
- src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStateManagerTests.java
- src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTests.java
- src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/DeleteTests.java
change setting name; fix stop AD request
> change setting name and fix stop AD request

- src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
- src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java
Current thresholding implementation depends on synchronous operations for checkpoint data. As part of the asynchronous paradigm migration, this change adds a new async getThresholdingResult method with the same business logic but async api.
> add async getThresholdingResult

- src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
- src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java
- src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManagerTests.java
- src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDaoTests.java
getFeaturesForSampledPeriods method returns training data for cold start. Its current implementation depends on synchronous api. As part of the asynchronous paradigm migration, this change adds a new async getFeaturesForSampledPeriods implementation using the same business logic.
> Add async getColdStartData

- README.md
> Change to mention we support only JDK 13

- .github/workflows/test-workflow.yml
This PR updated the branch to be tested in the github workflow from development to master.
> Update test branch

- src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
* change AD result index rollover setting (#100)
> change AD result index rollover setting (#100)

- src/main/java/com/amazon/opendistroforelasticsearch/ad/model/DetectorProfile.java
DetectorProfile's merge method does not include new fields added.  This PR fixes that.
Testing done:
* Manually verified profile API works as expected
> Fix bug in profile API

- opendistro-elasticsearch-anomaly-detection.release-notes.md
- release-notes/release-notes-odfe-1.7.0.md
Adds initial release notes for ODFE 1.7.0.
> Add release notes for ODFE 1.7.0

- src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestStatsAnomalyDetectorAction.java
Previously, we use index stats to retrieve doc count. But the stats are emitted by Lucene and include nested doc count.  Since our detector index uses nested type for the feature_attributes field, stats API would overcount the number of docs.
This PR restores to use search all of the index docs and fetch total hits as doc count.
Testing done:
* manually verified by starting a local cluster
> Backport: Fix incorrect detector count in stats APIs (#129)

- build.gradle
> Upgrade job scheduler spi

- release-notes/opendistro-for-elasticsearch-anomaly-detection.release-notes-1.8.0.0.md
> Add 1.8.0 release notes

- release-notes/opendistro-for-elasticsearch-anomaly-detection.release-notes-1.8.0.0.md
https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/222
> Add breaking changes in release notes

- src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
- src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManagerTests.java
this pr removes deprecated getCurrentFeatures code
> remove deprecated getCurrentFeatures

- src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/HybridThresholdingModel.java
- src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
- src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/HybridThresholdingModelTests.java
- src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java
> merge from master to 1.8.0

- src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/HybridThresholdingModel.java
- src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
- src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/HybridThresholdingModelTests.java
- src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java
This pr cherrypicks a few changes for 1.4 branch.
> chery pick changes for 1.4 branch

- .github/draft-release-notes-config.yml
- .github/workflows/draft-release-notes-workflow.yml
Add auto release drafter
Example on my repo [release](https://github.com/yizheliu-amazon/anomaly-detection/releases):
> Add auto release drafter

- .github/workflows/CI.yml
- README.md
- build.gradle
Add badges to README
Similar to AD Kibana: https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/pull/262
Test example branch: https://github.com/opendistro-for-elasticsearch/anomaly-detection/tree/badges-test
> Add badges to AD

- cli/cmd/profile.go
Change table from right aligned to left aligned.
For better UX, changed alignment from right to left.
Before:
After:
> Change Profile List Format

- release-notes/opendistro-for-elasticsearch-anomaly-detection.release-notes-1.10.1.0.md
Added release notes with categories and corresponding PR.
> Include release notes for 1.10.1.0

- build.gradle
Fix build failure due to merge commit
> Fix build failure

- build.gradle
FIx build failure of common util lib.
> fix build issue of common util

- src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java
- src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorResponse.java
- src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorActionTests.java
*Issue #195 *
Adding detector to Create/Update detector response
> Adding detector to Create/Update detector response

- build.gradle
- src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorTransportAction.java
- src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorTransportAction.java
- src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyResultTransportAction.java
- src/main/java/com/amazon/opendistroforelasticsearch/ad/util/ParseUtils.java
- src/main/java/com/amazon/opendistroforelasticsearch/ad/util/RestHandlerUtils.java
- src/test/java/com/amazon/opendistroforelasticsearch/ad/util/ParseUtilsTests.java
We changed AD index mapping to use nested type for user field (#291 ). This PR is to update user role filter to nested query.
> update user role filter to use nested query

- src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/StatsAnomalyDetectorTransportAction.java
*Issue #195 *
Adding support to access Stats information. 
> Stashing context for Stats API to allow users to query from RestAPI

- release-notes/opendistro-for-elasticsearch-anomaly-detection.release-notes-1.12.0.0.md
update release notes for 1.12.0.0
> update release notes for 1.12.0.0

- build.gradle
Without backporting, 1) AD won't support single-core instance types like t2.small; 2) cold start can fail endlessly.
Testing done:
1. We have correctness tests using RCF.  The test passed.
> backport PR 150, 239

- src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
> backport PR 310: fix double nan error when parse to json

- build.gradle
Without backporting, cold start can fail.
Testing done:
1. We have correctness tests using RCF.  The test passed.
> backport PR 239

- release-notes/opendistro-for-elasticsearch-anomaly-detection.release-notes-1.13.0.0.md
update release note to include #385
> update release note to include #385

- src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunner.java
> Backport part of PR 374: enforce init progress to use ASCII explicitly

- src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/DeleteAnomalyDetectorTransportAction.java
PR 320: https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/320/files
> Backport PR 320
