opendistro-for-elasticsearch/anomaly-detection

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/breaker/ADCircuitBreakerService.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/breaker/BreakerName.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/breaker/CircuitBreaker.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/breaker/MemoryCircuitBreaker.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/breaker/ThresholdCircuitBreaker.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/breaker/ADCircuitBreakerServiceTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/breaker/MemoryCircuitBreakerTests.java

#6 
Currently we have only memory circuit breaker for AD.

Circuit breaker service

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/breaker/ADCircuitBreakerService.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonErrorMessages.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/RCFResultTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/breaker/ADCircuitBreakerServiceTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/RCFResultTests.java

Circuit breaker

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestDeleteAnomalyDetectorAction.java

Stop detector API use wrong request type DeleteDetectorRequest. That will delete detector wrongly. 
This PR changes to correct request and has passed end to end test.

fix stop detector api to use correct request

---

build.gradle

build artifacts for rpm, deb, zip

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java

This pr adds support for the window delay field. It is designed to allow real-time data enough time to arrive at the cluster. When set, the data used for detection is from window delay ago rather than current time.
Passed e2e test.

add window delay support

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManagerTests.java

Current preview returns an internal exception when there is no data. For an example, see https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/28 This pr handles the case with a clear error message, as shown below.
````
[elasticsearch] java.lang.IllegalArgumentException: No data to preview anomaly detection.
[elasticsearch]         at com.amazon.opendistroforelasticsearch.ad.feature.FeatureManager.lambda$getPreviewFeatures$14(FeatureManager.java:277) [opendistro-anomaly-detection-1.2.1.0-alpha.jar:1.2.1.0-alpha]
[elasticsearch]         at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) [elasticsearch-7.2.1.jar:7.2.1]
[elasticsearch]         at com.amazon.opendistroforelasticsearch.ad.feature.FeatureManager.lambda$getSamplesForRanges$19(Featur …
```

return no data error message to preview

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/model/IntervalTimeConfiguration.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/IntervalTimeConfigurationTests.java

The value of window delay is by design non-negative. This change allows the zero value when there is no need for any delay.

allow non-negative window delay

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRunner.java

When previewing anomaly results encounters an issue, the response is empty instead of an exception to the kibana frontend and the cause is logged with info.
```
[elasticsearch] [2020-01-14T18:20:00,979][INFO ][c.a.o.a.AnomalyDetectorRunner] [node-0] Fail to preview anomaly detector W0n_pm8B_IjOQi-ITIdN
[elasticsearch] java.lang.IllegalArgumentException: No data to preview anomaly detection.
[elasticsearch]         at com.amazon.opendistroforelasticsearch.ad.feature.FeatureManager.lambda$getPreviewFeatures$14(FeatureManager.java:296) [opendistro-anomaly-detection-1.2.1.0-alpha.jar:1.2.1.0-alpha]
[elasticsearch]         at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) [elasticsearch-7.2.1.jar:7.2.1]
[elasticsearch]         at …
```

return empty preview results on failure

---

build.gradle
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/DailyCron.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/MasterEventListener.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/ClientUtil.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/DailyCronTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/MasterEventListenerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndicesTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStateManagerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStatsTransportActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/util/IndexUtilsTests.java

Use ClientUtil so that we have a consistent place to control index access.
Testing done:
* all tests passed
* run end-to-end testing to verify basic workflow works including creating detector and generate anomaly score

Refactor using ClientUtil

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManagerTests.java

Currently, for preview requests, up to 60 data points are sampled and up to 200 results are returned to the client to reduce latency from processing and network. To improve visualization for human eyes, the changes increase the number of samples to match the requested time range, the upper limit of samples, and the number of returned results to clients.

adjust preview configuration for more data

---

build.gradle
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorJob.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestAnomalyDetectorJobAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestDeleteAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestGetAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/AnomalyDetectorActionHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/AnomalyDetectorFunction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/RestHandlerUtils.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/util/RestHandlerUtilsTests.java

* Add job disabled time
* Support return AD job when get detector if set `?job=true`
* Tune start job logic: 
1). If job not exists, create new job.
2). If job exists: a). if job state is enabled, return warning message; b). if job state is disabled, enable job.
* Tune stop job logic:
1). If job not exists, return error message
2). If job exists: a).if job state is disabled, return warning message; b).if job state is enabled, disable job and stop AD model.
* Tune delete detector logic:
1). If no AD job index or AD job not found or AD job is disabled, delete detector directly
2). If AD job state is enabled, return warning message, not delete detector

support return AD job when get detector

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorJobRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java

When we run AD and SQL plugin together, ES fails to start with registering a setting twice error. AD's threadpool setting prefix is null. Since SQL plugin uses null as well, we would have a register setting conflict because we cannot register setting [null.size] twice. The fix is to give our threadpool a setting name prefix instead of null
Also, this threadpool would be used by other components besides AD job.  Rename it to make it not ad job specific.
Testing done:
- run all unit and integration tests
- ES can start with AD and SQL plugin enabled

Add threadpool prefix and change threadpool name

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java

A connection request to a threshold model node can be rejected.  Previously, we count exceptions due to connection problem as "unexpected". But we should not as this might happen when the cluster is unstable.  This PR fixes the log message.
Testing:
- unit and integration test pass

Improve log message when we cannot get anomaly result

---

README.md
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java

*Issue #, if available:* 
https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/57
This PR change build instruction for JDK as we have a build error using JDK 13. This PR also fixes a grammar issue in the log message.

Change build instruction for JDK

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDaoTests.java

Adds the asynchronous implementation of getFeaturesForPeriod without business logic changes to deprecate the current synchronous implementation.

Add async implementation of getFeaturesForPeriod.

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java

Current models used output preview results are randomized. To produce more deterministic results in preview, random seeds used in the models are fixed with this change.

fix rcf random seed in preview

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/CheckpointDao.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/CheckpointDaoTests.java

This change adds async operations for putting, getting, and deleting checkpoints. In the overall effort of moving towards asynchronous implementation, the new async operations will replace current synchronous operations used for model management.

Add async CheckpointDao methods.

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java

Current rcf scoring implementation depends on synchronous operations for checkpoint data. As part of the asynchronous paradigm migration, this change adds a new async getRcfResult method with the same business logic but async api.

add async getRcfResult

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestExecuteAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/ParseUtils.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManagerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDaoTests.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/64
Preview does not use all data in the given time range as it is costly. Previously, we sample data by issuing multiple queries on shard 0 data. The purpose of the shard 0 query restriction is to reduce system costs. The nab_art_daily_jumpsup data set has one doc in each interval, and the doc is spread out in 5 shards. Even though we issue 360 queries, we only get 70~80 samples back by querying shard 0. Together with interpolated data points, the preview run misses significant portions of data required to train models (400 is the minimum) and thus returns empty preview results. This PR fixes the issue by removing the shard 0 search restriction.
Previously, the …

Fix empty preview result due to insufficient sample

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyResult.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/73
Recently, we changed the anomaly result index’s schema and toXContent method by introducing new fields. During the preview, some of the fields in anomaly result index are null. Thus, toXContent fails with a null pointer exception.
This PR fixes the issue by protecting a field’s serialization with a null check.
This PR also removes an unused local variable in ModelManager.
Testing done:
- Manually verified the issue is gone
- gradle build

Fix null pointer exception during preview

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorExecutionInput.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestExecuteAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/RestHandlerUtils.java
src/main/resources/mappings/anomaly-detectors.json
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorExecutionInputTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/util/RestHandlerUtilsTests.java

*Issue #71
1.Support previewing detector on the fly. If user pass detector in preview API, will preview the detector directly without saving and retrieving it.
2.Remove useless fields in detector index mapping

preview detector on the fly

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandler.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java

*Issue #75
1.Check if feature list is null or not when convert `AnomalyDetector` to `XContentBuilder`
2.Will not start AD job if detector has no features.

Can't start AD job if detector has no feature

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStateManagerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/util/IndexUtilsTests.java

The PR does the following:
1. Change the default value of lastUpdateTime from the current timestamp to null. Before the change, creating a detector returns one lastUpdateTime, while getting a detector returns a different lastUpdateTime. The difference is confusing to the user, and they may wonder what has happened between the creating and getting detector calls. After the change, creating a detector returns no last update time, while getting a detector returns a last update time.
2. Replace the mocked threadpool in 2 tests with a real threadpool object.
Testing done:
1. verified lastUpdateTime change in a cluster
2. gradle build
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …

Change the default value of lastUpdateTime

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java

This change adds a new async trainModel implementation with the same business logic to replace the current synchronous implementation.

add async trainModel

---

build.gradle

*Issue #79 *
The build process failed on Windows because of a UNIX-specific path. During the build, there would be an attempt to download the file from the local file system which would result in an error, as shown in issue #79 . 
The change included adding a remote URL from which the job-scheduler plugin would be downloaded instead of a local file reference.

Added URL for jb_scheduler-plugin_zip instead of local file path

---

build.gradle
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorJobRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStateManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/RCFResultTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/StopDetectorTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ThresholdResultTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/handler/AnomalyResultHandler.java
src/main/resources/mappings/anomaly-results.json
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorJobRunnerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/ADClusterEventListenerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManagerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDaoTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStateManagerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/CronTransportActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/DeleteModelTransportActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/RCFResultTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ThresholdResultTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/util/IndexUtilsTests.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/78
This PR includes the following changes:
1. remove classes that are not needed in jacocoExclusions since we have enough coverage for those classes.
2. Use ClientUtil instead of Elasticsearch’s client in AD job runner
3. Use one function to get the number of partitioned forests. Previously, we have redundant code in both ModelManager and ADStateManager.
4. Change ADStateManager.getAnomalyDetector to use callback.
5. Change AnomalyResultTransportAction to use callback to get features.
6. Add in AnomalyResultTransportAction to handle the case where all features have been disabled, and users' index does not exist.
7. Change get RCF and threshold result methods to use …

Use callbacks and bug fix

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/ADClusterEventListener.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/HashRing.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/HourlyCron.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/MasterEventListener.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonName.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestStatsAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStatsNodeRequest.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStatsRequest.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/StopDetectorTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/ClusterStateUtils.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/ADClusterEventListenerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/HashRingTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/HourlyCronTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/MasterEventListenerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStatsIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStatsTests.java

Ultrawarm introduces warm nodes into the ES cluster. Currently, we distribute model partitions to all data nodes in the cluster randomly, which could cause a model performance downgrade issue once warm nodes are throttled due to resource limitations. The PR excludes warm nodes to place model partitions.
Since index shards are hosted on hot nodes, AD's coordinating nodes are in hot nodes as well. We don't need to send HourlyCron job and stats requests to warm nodes anymore. This PR implements those changes.
Testing done:
1. Verified AD runs only in hot nodes.
2. stats API and HourlyCron still works.

Integration with Ultrawarm

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java

* Change AD result index  rollover setting
1. Roll over AD result index every 30 days, or
2. Roll over AD result index if doc count exceeds 300k. 
> Suppose generally per cluster has 200 detectors and all run with 1 minute interval. We will get 288,000 AD result docs. So set it as 300k to avoid multiple roll overs per day.

change AD result index rollover setting

---

README.md
build.gradle

bump opendistroVersion to 1.6.1

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorJobRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/ColdStartRunner.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTests.java

We expect an EndRunException to be thrown due to missing training data.  But the exception is not appropriately propagated back to AD job and results in InternalFailure instead.  This PR fixes the bug.
Testing done:
1. Manually reproduced all  possible EndRunExceptions, check AD job is terminated, and check profile API status is correct.
2. Added unit tests to expose the bug.
Profile output for init failures:
[2020-05-02 14:17:31 PDT] [2020-05-02 21:17:31 UTC]
kaituo@dev-dsk-kaituo-2a-74e3f324.us-west-2: ~/code/github/anomaly-detection
% curl -X GET "localhost:9200/_opendistro/_anomaly_detection/detectors/fu8z13EBn03yvIf6cLBm/_profile"
{"state":"DISABLED","error":"Stopped detector as job failed consecutively for more than 3 times: Cannot …

Fix that AD job cannot be terminated due to missing training data

---

build.gradle
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonErrorMessages.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/AbstractSearchAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestAnomalyDetectorJobAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestDeleteAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestExecuteAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestGetAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestIndexAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestStatsAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/EnabledSetting.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/e2e/DetectionResultEvalutationIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java

This PR adds settings to disable/enable AD dynamically.  AD plugin rejects RESTful requests and stops AD jobs when it is disabled.
Testing done:
- added tests to verify if AD plugin rejects RESTful requests when it is disabled
- manually verified AD jobs are stopped when AD plugin is disabled
Usage:
```
curl -XPUT "localhost:9200/_cluster/settings" -H 'Content-Type: application/json' -d'
{
"persistent": {
"opendistro.anomaly_detection.enabled": false
}
}'
```

Add settings to disable/enable AD dynamically

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/CheckpointDao.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/CheckpointDaoTests.java

Current asynchronous putModelCheckpoint implementation does not include timestamp. This change adds to checkpoint data the timestamp at which it is made for cleanup.
Below is an example of mode checkpoint data.
`
{'model' : '...',
'timestamp': '2020-04-28T16:40:18.096676Z'}
`

add timestamp to async putModelCheckpoint

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java

Current clearModel is a synchronous operation for deleting models. As part of migration to asynchronous implementation, this change adds an asynchronous implementation with the same business logic as the current one.

Add async clear

---

settings.gradle

Previously, rpm and deb is named as "opendistro-anomaly-detector-1.7.0.0-1.noarch.rpm" and "opendistro-anomaly-detector_1.7.0.0-1_amd64.deb" respectively, whle zip is named as "opendistro-anomaly-detection-1.7.0.0.zip".
After the fix, they are named as:
opendistro-anomaly-detection_1.7.0.0-1_amd64.deb
opendistro-anomaly-detection-1.7.0.0-1.noarch.rpm
opendistro-anomaly-detection-1.7.0.0.zip

Change setting name so that rpm/deb has the same name as zip

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java

Current stopModel is a synchronous operation for stopping hosting models. As part of migration to asynchronous implementation, this change adds an asynchronous equivalent using the same business logic with one minor change/fix - setting lastCheckpointTime on a stopped and saved model object going into garbage collection is unnecessary and is therefore removed for cleanness.

add async stopModel

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonName.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/DetectorProfile.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/ModelProfile.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/ProfileName.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestGetAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileNodeRequest.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileNodeResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileRequest.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AbstractADTest.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunnerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileTransportActionTests.java
src/test/java/test/com/amazon/opendistroforelasticsearch/ad/util/JsonDeserializer.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/111
Hash ring helps identify node X runs the AD job for a detector Y with models on node 1,2,3.  This helps oncalls locate logs. Total model size gives transparency relating to the current memory usage. What's more, shingle size help answer question "why my detector does not report anything?"
This PR adds the above info to profile API via a broadcast call that consults ModelManager and FeatureManager about current state pertaining to a detector.  Then these states are consolidated into information humans can parse.
This PR also queries all AD result indices instead of only current result index so that we can fetch a stopped detector's error after the result index …

Add shingle size, total model size, and model's hash ring to profile API

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java

The current maintenance is a synchronous operation for removing stale hosted models and updating persisted checkpoints. As part of migration to asynchronous implementation, this change adds a new asynchronous operation with the same business logic as the current one.

add async maintenance

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunner.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunnerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/111
Previously, profile API scans all anomaly result indices to get a detector's most recent error, which can cause performance bottleneck with large anomaly result indices. This PR improves this aspect via various efforts.
First, when a detector is running, we only need to scan the current index, not all of the rolled over ones since we are interested in the latest error.
Second, when a detector is disabled, we only need to scan the latest anomaly result indices created before the detector's disabled time.
Third, setting track total hits false makes ES terminate search early. ES will not try to count the number of documents and will be able to end the query as soon …

Improve profile API's error fetching efficiency

---

opendistro-elasticsearch-anomaly-detection.release-notes.md
release-notes/release-notes-odfe-1.7.0.md

Adds initial release notes for ODFE 1.7.0. Is consistent with release notes for corresponding Kibana plugin.
Will put out following PR to backport changes to opendistro-1.7 branch.

Add release notes for ODFE 1.7.0

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorJobRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/ColdStartRunner.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndicesTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTests.java

This PR forward porting https://github.com/opendistro-for-elasticsearch/anomaly-detection/commit/b351d409bb61453bb656ad5ac1acf067fd223f17

Forward porting "Fix that AD job cannot be terminated due to missing training data"

---

build.gradle
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonErrorMessages.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/AbstractSearchAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestAnomalyDetectorJobAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestDeleteAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestExecuteAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestGetAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestIndexAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestStatsAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/EnabledSetting.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/e2e/DetectionResultEvalutationIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java

This PR adds settings to disable/enable AD dynamically.  AD plugin rejects RESTful requests and stops AD jobs when it is disabled.
Testing done:
- added tests to verify if AD plugin rejects RESTful requests when it is disabled
- manually verified AD jobs are stopped when AD plugin is disabled

Forward portting "Add settings to disable/enable AD dynamically (#105)"

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonName.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/DetectorProfile.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/ModelProfile.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/ProfileName.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestGetAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileNodeRequest.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileNodeResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileRequest.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AbstractADTest.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunnerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileTransportActionTests.java
src/test/java/test/com/amazon/opendistroforelasticsearch/ad/util/JsonDeserializer.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/commit/e06cf6f11e86da9f1679057080184257d384fed4
https://github.com/opendistro-for-elasticsearch/anomaly-detection/commit/85d276887c2e1f6c529a1a58a6daff74cf28669f
https://github.com/opendistro-for-elasticsearch/anomaly-detection/commit/a40ccf6510d485b4053a8f9c69fcde13a8480732

Forward porting profile API related PRs

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestStatsAnomalyDetectorAction.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/123
Previously, we use index stats to retrieve doc count. But the stats are emitted by Lucene and include nested doc count.  Since our detector index uses nested type for the feature_attributes field, stats API would overcount the number of docs.
This PR restores to use search all of the index docs and fetch total hits as doc count.
Testing done:
* manually verified by starting a local cluster

Fix incorrect detector count in stats APIs

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestIndexAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java

* fix dynamic setting of max detector/feature limit
```
PUT _cluster/settings
{
"transient" : {
"opendistro.anomaly_detection.max_anomaly_detectors" : 1
}
}
```
Create the second detector and will get error:
```
{
"error": {
"root_cause": [
{
"type": "illegal_argument_exception",
"reason": "Can't create anomaly detector more than 1"
}
],
"type": "illegal_argument_exception",
"reason": "Can't create anomaly detector more than 1"
},
"status": 400
}
```

fix dynamic setting of max detector/feature limit

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java

#118 
Add logic to prevent user from creating detector with duplicate name
Testing:
```
./gradlew build
./gradlew integTest
```
Manual testing:
```
// create detector cli-d-1-min-001
~/Downloads [ curl -X POST "localhost:9200/_opendistro/_anomaly_detection/detectors" -H 'Content-Type: application/json' -d'                                               ] 5:09 PM
{
"name":"cli-d-1-min-001",
"description":"Test nab daily jumpsup",
"time_field":"timestamp",
"indices":[
"test-index"
],
"feature_attributes":[
{
"feature_name":"feature-1",
"feature_enabled":true,
"aggregation_query":{
"value_sum":{
"sum":{
"field":"feature-1"
}
}
}
}
],
"detection_interval":{
"period":{
"interval":1,
"unit":"Minutes"
}
}
}
' …
```

Prevent creating detector with duplicate name. Issue:#118

---

.github/workflows/CD.yml
.github/workflows/CI.yml
src/test/java/com/amazon/opendistroforelasticsearch/ad/e2e/DetectionResultEvalutationIT.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/104
This PR adds CI/CD workflows. CI workflow builds a zip file, installs that on the official ODFE docker image, and runs rest test case. CI workflow is triggered by branch pushing. CD workflow builds zip, rpm, deb files, and uploads those files to s3. CD workflow is triggered by tag creation.
This PR also increases model initialization waiting time as needed on DetectionResultEvalutationIT as it can be long on a remote cluster.
Testing done:
* ran the scripts on CI/CD workflow manually and tested it works.
* made sure local gradle build time does not increase due to my change in DetectionResultEvalutationIT.
By submitting this pull request, I confirm that you can …

Add CI/CD workflows

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManagerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDaoTests.java

This pr deletes deprecated code for getFeatureSamplesForPeriods and getPreviewFeatures methods.

delete deprecated getFeatureSamplesForPeriods getPreviewFeatures

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java

The current system updates thresholding models with any scores, including zero anomaly scores. Zero scores lower the threshold and result into more false positives later on when the scores become non-zero. This change skips zero scores for updating thresholding models.

not update threshold with zero scores

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/HybridThresholdingModel.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/HybridThresholdingModelTests.java

Current thresholding model outputs anomaly grade nan when it has not been updated any data. This change makes the output grade zero to make results clearer.

threshold model outputs zero grades instead of nan grades

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java

This pr configures rcf with a lower number of samples for scoring. The current configuration is 256 samples and the new configuration is 128. Rcf confidence remains unchanged 0 for samples from 128 to 256 due to low sample size.

configure rcf with new minimum samples

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java

Currently, we roll over the result index every 30 days or every 300000 docs. Assuming each doc has 1 KB and our result index has five shards, each shard takes about 60 MB, which is too small. Small shards are against ES best practice. This PR increases the rollover threshold to 9000000 docs, which increases the max shard size to roughly 1.8 GB. 

Rollover AD result index less frequently

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDaoTests.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/166
Currently, for sparse data (e.g., we only have docs half an hour every day), the preview/prediction API cannot find aggregated value and thus doesn't work.
This PR mitigates the sparse data issue by using an aggregation's default value if any.
Testing done:
1. Without this PR, preview/prediction cannot find any features to use given sparse data for cardinality aggregation. With this PR, preview/prediction can.
2. Verified no unexpected exceptions are thrown with this PR during prediction or preview.

Use aggregation's default value if no docs

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/breaker/ADCircuitBreakerService.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/LimitExceededException.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/EnabledSetting.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/143
https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/159
A circuit breaker is broken when heap memory usage exceeds 85%, and the related AD job would be disabled because of that. It is possible at one point the heap memory usage exceeds 85% and gets back to less than 85% soon afterward.
This PR mitigates the issue in the two following ways:
First, only disable the AD job after the circuit breaker is broken for a consecutive number of times (3 times).
Second, add a setting for enabling/disabling circuit breaker.
Testing done:
1. After disabling circuit breaker, an open circuit breaker does not affect AD job execution.
2. Verified an open …

Add setting for enabling/disabling circuit breaker

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndices.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/indices/RolloverTests.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/37
Currently we never delete the result index, even though customers have deleted the detector.   An increasing amount of result indices can use significant disk space, as well as memory pressure due to the creation of rolled over indices. This PR adds retention period to anomaly results.  We delete result indices when they are older than a retention period, which is 90 days by default. We use 90 days because that's the maximum days we allow users to view results on Kibana.  Users can configure the retention period via the setting opendistro.anomaly_detection.ad_result_history_retention_period dynamically.
Also, previously we roll over empty result indices.  This PR …

Add result indices retention period

---

release-notes/opendistro-for-elasticsearch-anomaly-detection.release-notes-1.9.0.0.md

Add release notes for ODFE 1.9.0.0

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/170
We have the following two memory threshold:
* a detector's model size per node cannot exceed 10% of heap memory
* the total model size per node cannot exceed 10% of heap memory.
If users use the ES cluster mainly for anomaly detection, they should be able to increase the memory for AD.  This PR makes the threshold dynamically adjustable via the setting opendistro.anomaly_detection.model_max_size_percent.
Testing done:
* Manually verified I can dynamically adjust the memory threshold setting.  

Add dyanmic setting for memory threshold

---

.github/workflows/CI.yml
build.gradle
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ODFERestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/e2e/DetectionResultEvalutationIT.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/142
This change is to support integration testing against remote security-enabled clustering in our CI. Currently, we only support the integration testing without a security plugin and have to remove the security plugin in CI.
The critical change is to create an https client with basic auth in ODFERestTestCase and let our rest test case inherit from ODFERestTestCase. With default security configuration, the password for the admin user is also “admin.” For ssl certification, we choose to disable it since it’s the default demo cert used here.
Testing done:
* ran the scripts on CI workflow on Mac and tested it works.
* gradle build still passes.
By submitting this pull …

Support security plugin enabled testing in CI

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonErrorMessages.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManagerTests.java

*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/180
*Description of changes:* This pr uses a robust exhaustive search for collecting training data samples at model creation time so the process is the best-effort against missing data in indices. For more discussion, use the issue above.

change to exhausive search for training data

---

.github/draft-release-notes-config.yml

*Issue #, if available:* #190 
This PR changes the draft release notes format to match the unified ODFE format.
Specifically:
- changes the `-` to a `*` for each change
- removes the `PR ` prefix for each change
- changes header size of categories from header 2 -> header 3
- sets categories to be the standard set of 8

Automate release notes to unified standard

---

.github/workflows/CI.yml
.github/workflows/esad-cli-publish-artifact-workflow.yml
.github/workflows/esad-cli-test-and-build-workflow.yml
README.md
cli/README.md
codecov.yml

Add badge and update publish only if tag is created.

Test code coverage

---

.github/workflows/CI.yml

*Issue #194 :*
*Description of changes:* Adding multinode integration test as part of CI

Adding multinode integration test support

---

cli/cmd/create.go
cli/cmd/profile.go
cli/cmd/root.go

1) Improve profile display if no profiles are found
Before:
After:
2) Refactor for readability
3) Delete binary file.

Improve ux

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestIndexAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
src/main/resources/mappings/anomaly-detectors.json
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManagerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java

- This change adds a new `windowSize` instance variable to the AnomalyDetector class along with a public getter for this variable, which the model uses to determine the shingle size. 
- The Create Detector and Update Detector APIs allow `window_size` to be set per detector. If no `window_size` param is provided, the default is set to 8.
- The Get Detector, Preview Detector, and Search Detector APIs will also reflect the `window_size` value in the API response.
- The FeatureManager and ModelManager classes have `shingleSize` removed as instance variables, and instead gets the shingle size from the anomaly detector that is passed to their methods.
- The `maxMissingPoints` (that determines how many data points can be missing and still form a valid shingle) is set to …

Allows window size to be set per detector.

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunner.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunnerTests.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/198
Currently, the progress bar on AD Kibana will show the estimated time remaining to initialize a detector. This can be confusing if this message is displayed before cold start is finished, where the actual initialization time may be much shorter if sufficient historical data exists. This PR changes the profile api to not return any estimated time left until the cold start is finished to prevent this.
Testing done:
1. Manually verified the problem is fixed.
2. added unit test for the issue.
Before the PR:
kaituo@dev-dsk-kaituo-2a-74e3f324.us-west-2: ~
% curl -XGET "http://localhost:9200/_opendistro/_anomaly_detection/detectors/F5nQ4HMBALosA6jhE7Ni/_profile?_all=true …

not return estimated minutes remaining until cold start is finished

---

cli/cmd/create.go
cli/cmd/delete.go
cli/cmd/profile.go
cli/cmd/root.go
cli/cmd/start_stop.go

minor edits to the short and long text strings

---

src/main/resources/mappings/anomaly-detector-jobs.json

Current job index mapping can't match the [model class](https://github.com/opendistro-for-elasticsearch/anomaly-detection/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorJob.java). AD job can run successfully. This PR fixes the job index mapping to match the model class.

fix job index mapping

---

cli/cmd/cat.go
cli/internal/controller/ad/ad.go
cli/internal/controller/ad/ad_test.go
cli/internal/controller/ad/mocks/mock_ad.go
cli/internal/controller/ad/testdata/get_response.json
cli/internal/entity/ad/ad.go
cli/internal/entity/ad/ad_test.go
cli/internal/gateway/ad/ad.go
cli/internal/gateway/ad/ad_test.go
cli/internal/gateway/ad/mocks/mock_ad.go
cli/internal/gateway/ad/testdata/get_result.json
cli/internal/handler/ad/ad.go
cli/internal/handler/ad/ad_test.go
cli/internal/mapper/ad/ad.go
cli/internal/mapper/ad/ad_test.go

Cat command to concatenate and print detectors
Added get method to get detector configuration

Get detector

---

.github/workflows/esad-cli-test-and-build-workflow.yml
cli/cmd/cat.go
cli/cmd/create.go
cli/cmd/delete.go
cli/cmd/profile.go
cli/cmd/root.go
cli/cmd/start_stop.go
cli/go.mod
cli/go.sum
cli/internal/client/request.go
cli/internal/controller/ad/ad.go
cli/internal/controller/ad/ad_test.go
cli/internal/controller/ad/mocks/mock_ad.go
cli/internal/controller/es/es.go
cli/internal/controller/es/es_test.go
cli/internal/controller/es/mocks/mock_es.go
cli/internal/entity/ad/ad_test.go
cli/internal/entity/es/es.go
cli/internal/gateway/ad/ad_test.go
cli/internal/gateway/ad/mocks/mock_ad.go
cli/internal/gateway/es/es_test.go
cli/internal/gateway/es/mocks/mock_es.go
cli/internal/gateway/gateway.go
cli/internal/handler/ad/ad_test.go
cli/internal/mapper/ad/ad_test.go

goimports fixes imports order and also formats like gofmt.

Use goimports instead of gofmt

---

.github/workflows/esad-cli-test-and-build-workflow.yml

go get inside cli will update the go.mod, since this is not part of code dependencies,
install goimports outside scope of cli.

Install go get outside cli directory

---

build.gradle
release-notes/opendistro-for-elasticsearch-anomaly-detection.release-notes-1.10.0.0.md

Added release notes with categories and corresponding PR.

Include release notes for 1.10.0.0

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java

*Description of changes:* remove unused deprecated code in model manager.

remove deprecated code

---

cli/cmd/cat.go
cli/cmd/create.go
cli/cmd/delete.go
cli/cmd/download.go
cli/cmd/root.go
cli/cmd/start_stop.go

Download configuration as files helps users to save it in source code control and maintains it.
This will also let users to share detector configuration across users.

CLI: Download Detector Configuration as File

---

cli/cmd/cat.go
cli/cmd/create.go
cli/cmd/delete.go
cli/cmd/profile.go
cli/cmd/root.go
cli/cmd/start_stop.go

To make it consistent, short message of commands first character
will be an uppercase ,flags first character will be lowercase.
Include Description as Header for command's long message.

CLI: Update Display Strings

---

cli/cmd/delete.go
cli/cmd/start_stop.go
codecov.yml

CLI: Fix build errors

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/AbstractSearchAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestSearchAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestSearchAnomalyResultAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyResultAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyResultTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyResultActionTests.java

Adding RestActions support for Search Rest API's.
- This is needed to integrate with Security plugin as it applies permissions based on Rest Actions.
- This is the first of the API's and work in progress for other APIs. Tests will be added soon.
*Issue #195 *

Adding RestActions support for AD Search Rest API's

---

build.gradle
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestStatsAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/stats/ADStatsResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/StatsAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/StatsAnomalyDetectorResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/StatsAnomalyDetectorTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/StatsAnomalyDetectorActionTests.java

*Issue #195 *
Adding RestActions support Detector Stats API which is needed for FGAC support. 

Adding RestActions support for Detector Stats API

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/RcfResult.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/rcf/CombinedRcfResult.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/RCFResultResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/RCFResultTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/RcfResultTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/rcf/CombinedRcfResultTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/RCFResultTests.java

*Description of changes:* This pr adds normalized anomaly score attribution to anomaly detection model output. Anomaly score is attributed to each feature dimension of a current single data point and normalized to 1 for easier consumption. Further changes to external API and persistence is not included in this pr.

add anomaly feature attribution to model output

---

build.gradle

This pr upgrades rcf libraries to the current version.

upgrade rcf libaries

---

cli/cmd/update.go
cli/internal/controller/ad/ad.go
cli/internal/controller/ad/ad_test.go
cli/internal/controller/ad/mocks/mock_ad.go
cli/internal/entity/ad/ad.go
cli/internal/gateway/ad/ad.go
cli/internal/gateway/ad/ad_test.go
cli/internal/gateway/ad/mocks/mock_ad.go
cli/internal/handler/ad/ad.go
cli/internal/handler/ad/ad_test.go
cli/internal/handler/ad/testdata/update.json
cli/internal/mapper/ad/ad.go
cli/internal/mapper/ad/ad_test.go

Update Detector Configurations

CLI: Update Detector Configurations

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultAction.java

*Issue #195 *
Modifying RestAction for Execute API which is needed for support AD FGAC

Modifying RestAction for Execute API

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonName.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestIndexAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorRequest.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AbstractADTest.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorTransportActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorActionTests.java
src/test/java/org/elasticsearch/action/admin/indices/mapping/get/IndexAnomalyDetectorActionHandlerTests.java

This PR adds categorical fields' number and type check. We only support one categorical field, and the categorical field can only be of type keyword and ip.  We also limit the max multi-entity detectors to 10.
Testing done:
1. added unit tests
2. did manual testing.

Verifying multi-entity detectors

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndices.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyResult.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/Entity.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ADResultBulkAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ADResultBulkRequest.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ADResultBulkTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndicesTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/indices/RolloverTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ADResultBulkTransportActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyResultActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/handler/AnomalyResultHandlerTests.java

Our performance evaluation has observed a large number of EsRejectedExecutionException due to indexing too many anomaly results. This PR adds a customized bulk transport action to deal with high index memory pressure. When the index pressure exceeds 80%, we only index non-zero anomaly grade index results and a random subset of zero anomaly grade index results.
This PR adds a few supporting data structures related changes:1. add constructors in AnomalyResult/FeatureData to use them in the newly added transport action.2. add Entity class to represent an entity in anomaly results.
This PR also renames ANOMALY_RESULT_INDEX to ANOMALY_RESULT_INDEX_ALIAS and moves it to the CommonName class. The name refers to an alias and is accessed in …

Selectively store anomaly results when index pressure is high

---

build.gradle
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorActionTests.java

*Issue #254 *
Ignoring this test for now as it is flaky in github runs. 
Will take care of it as part of the backlog.
Created a tracking issue #254 

Ignoring flaky test

---

build.gradle
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/caching/EntityCache.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/DetectorProfile.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/EntityProfile.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/ProfileName.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestGetAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/stats/StatNames.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityProfileAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityProfileRequest.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityProfileResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityProfileTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorRequest.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileNodeResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/MultiResponsesDelegateActionListener.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/RestHandlerUtils.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunnerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorTransportActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileTransportActionTests.java

Support high cardinality detector in profile API.
1.Total entity count
2.Active entity count
3.Profile entity status: active or not
Add job and detection state index in AD stats API
Did test by starting cluster locally for both single and HC detector.
Exclude some classes which coverage lower than our limitation. Will add more test case in another PR>

suppport HC detector in profile api

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java

Previously, our validation logic cannot parse nested fields from the getFieldMapping response because nested fields don't have the full name in the response.  For example, the field nested_host.host only has "host" in the type mapping instead of "nested_host.host".  This PR fixes that by not depending on field name when parsing the name type mapping.
Testing done:
1. manual testing passes.

Fix nested field issue

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/CheckpointDao.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityResultTransportAction.java

Our performance testing finds that our checkpoint queue can increase quickly.  This can happen during maintenance if there are a lot of entities in cache and very few cache swap outs happen in the past hour.  When an entity's state is swapped out, we try to save a checkpoint.  If we haven't done so for an entity within one hour, we put the checkpoint to a buffer and do a flush at the end of maintenance.  Since we only flush the 1st 1000 queued requeues to disk, a lot of requests may still wait in the queue until the next flush happens.  This is not ideal and can cause memory outages.
This PR triggers another flush after the previous flush finishes if there are a lot of queued requests.
This PR also corrects the LImitExceededException when …

Auto flush checkpoint queue if too many are waiting

---

release-notes/opendistro-for-elasticsearch-anomaly-detection.release-notes-1.11.0.0.md

Add release notes for 1.11.0.0. Will not merge until all PRs for this tag are finalized and merged.

Add release notes for 1.11.0.0

---

build.gradle
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorJobRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/caching/PriorityCache.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonName.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonValue.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/indices/ADIndex.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndices.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/CheckpointDao.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyResult.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestIndexAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityResultTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/ThrowingSupplier.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/ThrowingSupplierWrapper.java
src/main/resources/mappings/anomaly-detector-jobs.json
src/main/resources/mappings/anomaly-detectors.json
src/main/resources/mappings/anomaly-results.json
src/main/resources/mappings/checkpoint.json
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorJobRunnerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/caching/PriorityCacheTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityResultTransportActionTests.java

This PR updates the current AD index mapping if a new version is detected.  Previously, we didn't do so.  This will cause issues when upgrading AD binary version: newly added fields will not be searchable, though we can still send get requests to fetch them.
This PR also makes the cache miss handling setting a dynamic setting.
Testing done:
1. manual upgrade testing passes with fgac on and off.
2. will add unit tests later.

Upgrade mapping

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java
src/test/java/org/elasticsearch/action/admin/indices/mapping/get/IndexAnomalyDetectorActionHandlerTests.java

Fix issue where max number of multi-entity detector doesn't work for UpdateDetector
Currently we only check if max number of multi-entity detector is reached for CreateDetector, this is to add that check for UpdateDetector.

Fix issue where max number of multi-entity detector doesn't work for UpdateDetector

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonValue.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ADResultBulkAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStatsNodesAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyDetectorJobAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/CronAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/DeleteAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/DeleteModelAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityProfileAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityResultAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ProfileAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/RCFPollingAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/RCFResultAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyResultAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/StatsAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/StopDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ThresholdResultAction.java

*Issue #195 *
Renaming all actions to distinguish between Internal facing vs external facing.

Renaming all Actions to distinguish between internal and external facing

---

build.gradle
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/caching/CacheBuffer.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/caching/EntityCache.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/caching/PriorityCache.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/stats/suppliers/ModelsOnNodeSupplier.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AbstractADTest.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/caching/CacheBufferTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/caching/PriorityCacheTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/ModelManagerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/stats/ADStatsTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/stats/suppliers/ModelsOnNodeSupplierTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStatsNodesTransportActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/MultientityResultTests.java
src/test/java/test/com/amazon/opendistroforelasticsearch/ad/util/MLUtil.java

This PR fixes two issues for the stats API.
First, we didn't propagate multi-entity detectors' models execution exceptions for the remote invocation.  This problem may impact stats' API ability to report the total failures count and thus hide an issue we should have reported during monitoring.  This PR fixes the issue by collecting model host nodes' exceptions from coordinating nodes.
Second, we didn't show active multi-entity detectors' models information on stats API.  This PR places this information into stats API output.
This PR also adds unit tests for ModelManager.
Testing done:
1. added unit tests
2. manually verified the two issues are resolved.
Stats API output after my changes:
```
{
"anomaly_detectors_index_status": "green", …
```

Fix for stats API

---

build.gradle
docs/high-cardinality-rfc.md
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestSearchAnomalyDetectorInfoAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorInfoAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorInfoRequest.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorInfoResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorInfoTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/RestHandlerUtils.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorInfoActionTests.java

*Issue #195 *
Adding new Search Detector Info API to query total number of detectors and match name with existing detectors.
This API will search across all the detectors in detector index irrespective of User context.
Count Request: 
`GET _opendistro/_anomaly_detection/detectors/count`
Response: 
`{
"count" : 4,
"match" : false
}`
Match Request:
`GET _opendistro/_anomaly_detection/detectors/match?name=opendistro_ad`
Response:
`{
"count" : 0,
"match" : false
}`

Adding new Search Detector Info API 

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorTransportAction.java

We didn't return after sending back channel responses after one recent change.  Later, when we use the channel to send back responses again, we get " java.lang.IllegalStateException: Channel is already closed".  This PR fixes this issue.
This PR also removes a redundant setting.

Fix for get detector API

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorActionTests.java

*Issue #195 *
As count and match detectors is moved to Search Detector Info API, Search Detector API will now filter all queries with backend role filter if enabled.
Also will be making changes to Alerting plugin, where we query Detectors during create Monitor workflow. 

Updating Search Detector API to reject all queries other than BoolQuery

---

src/main/resources/mappings/anomaly-detector-jobs.json
src/main/resources/mappings/anomaly-detectors.json
src/main/resources/mappings/anomaly-results.json

We need to set the user type as nested, then we can use exists query to check if `user` and `user.backend_roles` exists

set user as nested type to support exists query

---

build.gradle

Exclude IndexAnomalyDetectorResponse from Jacoco to unblock build

Exclude IndexAnomalyDetectorResponse from Jacoco to unblock build

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestExecuteAnomalyDetectorAction.java

When FGAC enabled and preview detector with detector id, it throws no permission exception as can't read detector config index.

fix no permission when preview detector with detector id

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorJobRunner.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorJobRunnerTests.java

*Issue #195 *
Adding User role injection to AD background job runner
The changes are manually tested on a test domain.

Injecting User role for background job

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRunner.java

Fix edge case where entities found for preview is empty.
Have verified on test domain that empty result is returned with this fix.

Fix edge case where entities found for preview is empty

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyResultTransportAction.java

Detector has null user as we can't get user from thread context and we don't set user in detector when create/update detector.
Test locally and on test cluster.

fix null user in detector

---

build.gradle
src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/CheckpointDao.java

When cluster restarted, will restore model from checkpoint, but will throw fatal errors which will restart cluster.
```
[2020-10-29T19:43:34,676][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [ad5beb168c48658f8e0d1f227f3395cd] fatal error in thread [elasticsearch[ad5beb168c48658f8e0d1f227f3395cd][get][T#4]], exiting
java.lang.NoSuchMethodError: 'com.google.gson.JsonElement com.google.gson.JsonParser.parseString(java.lang.String)'
at com.amazon.opendistroforelasticsearch.ad.ml.CheckpointDao.lambda$fromEntityModelCheckpoint$12(CheckpointDao.java:469) ~[?:?]
at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
at com.amazon.opendistroforelasticsearch.ad.ml.CheckpointDao.fromEntityModelCheckpoint(CheckpointDao.java:467) …
```

fix fatal error of missing method parseString

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/EntityResultTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/handler/MultiEntityResultHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/Throttler.java

*Issue #299 *
Conflict Guice binding for Clock.

remove clock Guice binding

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java

HC detector stays on initialization for days. We can see a lot of “NoSuchElementException” exception which caused by `Optional.EMPTY.get()`. This caused by null feature aggregation result (the category field value is not null). So if some entities have null feature data, will throw `NoSuchElementException` exception and skip other normal entities.

filter out empty value for entity features

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/DailyCron.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/MasterEventListener.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/diskcleanup/IndexCleanup.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/cluster/diskcleanup/ModelCheckpointIndexRetention.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/MasterEventListenerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/diskcleanup/IndexCleanupTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/cluster/diskcleanup/ModelCheckpointIndexRetentionTests.java

Add checkpoint index retention logic for multi entity detectors.
*Testing:*
* UT - Done
* Functional testing in test domain - Done

Add checkpoint index retention for multi entity detector

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/stats/StatNames.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/MultientityResultTests.java

Add high cardinality detector request/failure stats

add HC detector request/failure stats

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorJobRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndices.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java

This PR fixes two bugs of upgrading mapping:
First, previously we only tried once when upgrading mapping.  It is possible we need to try a few more times.  The drawback is that if the code has a bug, we retry endlessly.  I should fix it in the future.
Second, we enclose the upgrade mapping function call under a user context in a recent commit.  Upgrade mapping will fail when security plugin is enabled since a regular user cannot upgrade mappings of system indices.
The PR also adds upper bounds to our dynamic settings if reasonable.
Testing done:
1. Tested that upgrade mapping succeeds with new changes.
2. Tested the upper bounds of the changed settings are in effect.
By submitting this pull request, I confirm that you can use, modify, …

Fix for upgrading mapping

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/RCFPollingTests.java

`new Gson().toJson(Double.NaN)` will throw such exception: "NaN is not a valid double value as per JSON specification"
This PR fixed this bug

fix double nan error when parse to json

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/ml/EntityColdStarter.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManagerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ml/EntityColdStarterTests.java

Fix issue where data hole exists for Preview API. For now, we only get cold start samples with non-zero doc, and we add samples to corresponding date range by [index of cold start samples](https://github.com/opendistro-for-elasticsearch/anomaly-detection/blob/2e7e39d01631e27822b64cdd93e75956d72efdf2/src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/FeatureManager.java#L607-L613). This can cause issue because when source data has no doc in periods of time, size of `featureSamples` is less than `sampleRanges`, then only the some beginning date ranges of `sampleRanges` have data returned.
Fix is simple: just include zero count bucket in the response from ES. 
Example: data only exists in source starting from 11-13-2020
Before: …

Fix issue where data hole exists for Preview API

---

.github/workflows/CI.yml

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/194
Add multi node integration testing into CI workflow
*Testing:* 

Add multi node integration testing into CI workflow

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/DeleteAnomalyDetectorTransportAction.java

*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/304
We should not delete detector if it's running.
Test: 
Run ./gradlew run and test deleting running detector will fail.

fix delete running detector bug

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/Feature.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorSerializationTests.java

Detector and feature serialization has issue, see such error:
```
[2020-12-03T03:10:00,566][ERROR][c.a.o.a.t.ADTaskManager  ] [node-1] Fail to execute batch task action BYSTJnYBeb-NN24R-TEn
org.elasticsearch.transport.RemoteTransportException: [node-3][127.0.0.1:9302][cluster:admin/opendistro/ad/detector/batch_run_remotely]
Caused by: java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.search.aggregations.PipelineAggregationBuilder][value]
at org.elasticsearch.common.io.stream.NamedWriteableRegistry.getReader(NamedWriteableRegistry.java:112) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:45) ~[elasticsearch-7.10.0.jar:7.10.0]
at …
```

fix detector and feature serialization

---

build.gradle
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/ParseUtils.java

*Description of changes:* Moving the common-utils library to 1.12.0.2 consume latest changes in the security plugin.
Refer to commit: https://github.com/opendistro-for-elasticsearch/security/commit/7131b6a7ed2716697d7425ed441dcb7484f0b4ef

Moving common-utils to 1.12.0.2

---

build.gradle
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/GetAnomalyDetectorTransportActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/StopDetectorActionTests.java

*Issue #195 *
Taking first stab at adding unit tests for newly added Transport Actions

Adding unit tests for Transport Actions

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/model/ADTask.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/ADTaskState.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/ADTaskType.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorType.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyResult.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/DetectionDateRange.java
src/main/resources/mappings/anomaly-detection-state.json
src/main/resources/mappings/anomaly-detectors.json
src/main/resources/mappings/anomaly-results.json
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDaoTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/ADTaskTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorSerializationTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyResultTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/DetectionDateRangeTests.java

Currently we only have realtime detector which can take streaming data and detect anomaly in realtime way. For historical detector, user can feed historical data and detect historical anomalies. When user start historical detector, we will start an AD task at backend and run it asynchronously. This PR is to add AD task and tune detector and AD result to support historical detector.
1. AD Task
When user start a historical detector, we will create a new AD task. We will record task state, progress and detector snapshot in task.
2. Detector changes
* Add detection date range: user can specify the historical date range to run anomaly detection
* Add detector type: this is to make the search and aggregation easier. When create detector, user doesn't need to fill this …

add AD task and tune detector&AD result data model

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/stats/InternalStatNames.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/stats/StatNames.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStatsNodesTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/StatsAnomalyDetectorResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/StatsAnomalyDetectorTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStatsNodesTransportActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/StatsAnomalyDetectorTransportActionTests.java

Add AD task stats for historical detector
1.`./gradlew build`
2.`./gradlew integTest -PnumNodes=3`

add ad task stats

---

build.gradle
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/SecureADRestIT.java

*Issue #195 *
Adding support for Security tests for AD.
These tests will be run as part of CI and also can be locally tested with a test cluster.
Running locally:
`-Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="docker-cluster" -Dhttps=true -Duser=admin -Dpassword=admin --tests "com.amazon.opendistroforelasticsearch.ad.rest.SecureADRestIT.*"`

Adding support for Security Test Framework

---

README.md

*Issue #195 *
Updating readme to include documentation of Secure tests

Updating Readme to include Secure tests

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/MemoryTracker.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/LimitExceededException.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/settings/AnomalyDetectorSettings.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/task/ADBatchTaskCache.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/task/ADTaskCacheManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/ADStatsNodesTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/task/ADTaskCacheManagerTests.java

Add AD task cache. We will put RCF&threshold model, shingle data, threshold model training data in cache. 
##
1.  `./gradlew build`
2. `./gradlew integTest -PnumNodes=3`

add AD task cache

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/EntityProfileRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonErrorMessages.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/EntityProfile.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/MultiResponsesDelegateActionListener.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AbstractProfileRunnerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunnerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/EntityProfileTests.java
src/test/java/org/elasticsearch/action/admin/indices/mapping/get/IndexAnomalyDetectorActionHandlerTests.java
src/test/java/org/elasticsearch/search/aggregations/metrics/CardinalityProfileTests.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/339
MultiResponsesDelegateActionListener helps send multiple requests asynchronously and return one final response altogether. While waiting for all inflight requests, the method respondImmediately and failImmediately can stop waiting and return immediately. While these two methods are convenient, it is easy to misuse them and cause bugs (see https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/339 for example). This PR removes the method respondImmediately and failImmediately and refactor profile runner to avoid using them.
This PR also stops printing out the unknown entity state since it is not useful.
Testing done:
1. Added unit tests to verify …

Fix the profile API returns prematurely.

---

.github/workflows/CI.yml
.github/workflows/esad-cli-test-and-build-workflow.yml
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/EntityProfileRunner.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonErrorMessages.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/EntityProfile.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/MultiResponsesDelegateActionListener.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AbstractProfileRunnerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunnerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/EntityProfileTests.java
src/test/java/org/elasticsearch/action/admin/indices/mapping/get/IndexAnomalyDetectorActionHandlerTests.java
src/test/java/org/elasticsearch/search/aggregations/metrics/CardinalityProfileTests.java

Besides backporting, this PR also:
First, it fixes another premature return in AnomalyDetectorProfileRunner.onInittedEver.
Second, it replaces set-env with GITHUB_ENV so that backport PR can invoke CI. The `set-env` command is disabled.
Testing done:
1. Verfied manually the new early return bug is fixed..
2. Manual tests to run profile calls for single-stream and multi-entity detectors for different phases of the detector lifecycle (disabled, init, running). Verified profile results make sense.

Backport: Fix the profile API returns prematurely. (#340)

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/AnomalyDetectionException.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/ClientException.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/EndRunException.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/LimitExceededException.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/ResourceNotFoundException.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/constant/CommonErrorMessages.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndices.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ADIntegTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDaoTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportActionTests.java

Backport this change: https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/341
1. Catch wrong feature query exception and stop detector
2. Some exceptions are caused by customer input, which not related with the code logic. Will filter out such exceptions so we can get the failure stats which caused by server error.
1. `./gradlew build`
2. `./gradlew integTest -PnumNodes=3 `
3. Start local cluster and test

backport change: filter out exceptions which should not be counted in failure stats

---

.github/workflows/CI.yml
.github/workflows/esad-cli-test-and-build-workflow.yml
src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/AnomalyDetectionException.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/ClientException.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/EndRunException.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/LimitExceededException.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/common/exception/ResourceNotFoundException.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDao.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndices.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorJobActionHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ADIntegTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/feature/SearchFeatureDaoTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/AnomalyDetectorRestApiIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportActionTests.java

Backport this change: https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/341
1. Catch wrong feature query exception and stop detector
2. Some exceptions are caused by customer input, which not related with the code logic. Will filter out such exceptions so we can get the failure stats which caused by server error.
1. `./gradlew build`
2. `./gradlew integTest -PnumNodes=3 `
3. Start local cluster and test

filter out exceptions which should not be counted in failure stats

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportActionTests.java

1.Add more IT cases for filtering out non-server exceptions for HC detector.
2.Address comments https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/344#discussion_r549845490

add IT cases for filtering out non-server exceptions for HC detector

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java

Tune invalid query checking, return false directly rather than reach end of for loop.

backport change of PR348: return directly for invalid query checking.

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java

Tune invalid query checking, return false directly rather than reach end of for loop.

backport change of PR 348: return directly for invalid query checking

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyResultTransportAction.java

Tune invalid query checking, return false directly rather than reach end of for loop.

backport change of PR348: return directly for invalid query checking

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorProfileRunner.java
src/test/java/org/elasticsearch/search/aggregations/metrics/CardinalityProfileTests.java

https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/339
Testing done:
1. Manually verified the issue has been fixed.
2. Reproduced the issue using an unit test and verified fix using the test.

Fix another case of the profile API returns prematurely

---

build.gradle
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestPreviewAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/PreviewAnomalyDetectorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/PreviewAnomalyDetectorRequest.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/PreviewAnomalyDetectorResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/PreviewAnomalyDetectorTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/PreviewAnomalyDetectorActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/PreviewAnomalyDetectorTransportActionTests.java

*Issue #195 *
Moving Preview API to transport layer

Moving Preview Anomaly Detectors to Transport layer

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/PreviewAnomalyDetectorTransportAction.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/SecureADRestIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/PreviewAnomalyDetectorTransportActionTests.java

*Issue #195 *
Added backend role based filtering for Preview API.
Added new integration tests to verify the behavior.

Adding role based filtering for Preview API

---

build.gradle
src/main/java/com/amazon/opendistroforelasticsearch/ad/util/ParseUtils.java

Backporting change https://github.com/opendistro-for-elasticsearch/anomaly-detection/commit/48ac4f78fdea29cd3a8ba6797eb37e6882f679be to opendistro-1.11

Moving common-utils to 1.11.1.0

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetector.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/RestSearchADTasksAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/rest/handler/IndexAnomalyDetectorActionHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/task/ADTaskManager.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/DeleteAnomalyDetectorTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchADTasksAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchADTasksTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyResultTransportAction.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/transport/handler/ADSearchHandler.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/ADIntegTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/HistoricalDetectorIntegTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/HistoricalDetectorRestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/model/AnomalyDetectorTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/HistoricalDetectorRestApiIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ADBatchAnomalyResultTransportActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyDetectorJobTransportActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/DeleteAnomalyDetectorActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/IndexAnomalyDetectorTransportActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchADTasksActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchADTasksTransportActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/SearchAnomalyDetectorActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/handler/ADSearchHandlerTests.java
src/test/java/org/elasticsearch/action/admin/indices/mapping/get/IndexAnomalyDetectorActionHandlerTests.java

1. When user update historical detector, check if there is running task, and user can't switch between realtime and historical.
2. When user delete historical detector, check if there is running task.
3. Add. new search API to support searching AD tasks.
1. `./gradlew build`
2. `./gradlew integTest -PnumNodes=3`

update/delete historical detector;search AD tasks

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndices.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/model/ADTask.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/task/ADTaskManager.java
src/main/resources/mappings/anomaly-detection-state.json
src/test/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndicesTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyDetectorJobTransportActionTests.java

1. Add user in AD task to support search AD task API
2. Add placeholder in detection state index mapping and inject detector index mapping in code. So we can only maintain detector index mapping in one place.
1. `./gradlew build`
2. `./gradlew integTest -PnumNodes=3`
3. Start cluster and test both backend role filtering enabled and disabled cases

add user in AD task

---

build.gradle

Rename artifact name for rpm and deb
`./gradlew buildPackages`

rename rpm/deb artifact name

---

src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/ADBatchAnomalyResultTransportActionTests.java

fix flaky test case
`./gradlew build`

fix flaky test case

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/task/ADTaskManager.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/AnomalyDetectorJobTransportActionTests.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/transport/DeleteAnomalyDetectorTransportActionTests.java

1. Only validate feature when start detector
2. Fix flaky test case

validate detector only when start detector; fix flaky test case

---

.github/workflows/CD.yml

Issue #, if available:
Description of changes:
The infrastructure team is separating the production and staging locations into different AWS accounts. Plugins need to modify their workflows to publish to the new locations.
This PR changes the CD workflow to add a build number and write the zip, deb, and rpm plugin artifacts to staging.artifacts.opendistroforelasticsearch.amazon.com.
Test Results:
https://github.com/gaiksaya/anomaly-detection/runs/1684584738?check_suite_focus=true
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Change release workflow to use new staging bucket for artifacts

---

.github/draft-release-notes-config.yml

Identical to the [AD Kibana plugin change](https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/pull/358).
Updates the config file to use the raw URL in the embedded link to simplify the creation of the release notes in the `release-notes` directory, per ODFE standards.

Update draft release notes config

---

release-notes/opendistro-for-elasticsearch-anomaly-detection.release-notes-1.13.0.0.md

Adds release notes for v1.13.0.0.

Add release notes for version 1.13.0.0

---

build.gradle
src/test/java/com/amazon/opendistroforelasticsearch/ad/ODFERestTestCase.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/e2e/DetectionResultEvalutationIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/HistoricalDetectorRestApiIT.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/rest/SecureADRestIT.java

Fix flaky integration test cases
1. Start local cluster with security plugin and run `./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="docker-cluster" -Dhttps=true -Dsecurity=true -Duser=admin -Dpassword=admin`
2. Start local cluster without security plugin and run `./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="docker-cluster" -Dhttps=false` and `./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="docker-cluster"`
3. `./gradlew build`
4. `./gradlew integTest -PnumNodes=3`
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

fix failed integration cases

---

.github/workflows/CI.yml
.github/workflows/draft-release-notes-workflow.yml

With the recent efforts to change the default branch name from `master` to `main`, some workflows had `master` hardcoded - this changes those to `main` instead.

Update default branch in workflows

---

.github/workflows/CI.yml
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndices.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/TestHelpers.java
src/test/java/com/amazon/opendistroforelasticsearch/ad/e2e/DetectionResultEvalutationIT.java

Previously, we registered AD indices as system indices as AD indices' names start with a dot. ES deprecates the creation of dot-prefixed index names except for hidden and system indices (https://github.com/elastic/elasticsearch/pull/49959). Starting 7.10, ES adds a dedicated thread pool for system index write operations. System index writes/reads have higher priority than user index writes/reads. For example, system index writes can be forced regardless of whether the current index pressure is high or not (https://github.com/elastic/elasticsearch/blob/242083a36e02496aae9214dc41b89372022e7076/server/src/main/java/org/elasticsearch/index/IndexingPressure.java#L62-L73). 
AD indices are not more important than other user indices. We don't …

Change AD indices to be hidden indices instead of system indices.

---

src/main/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndices.java

This PR fixes a bug where hidden index setting was overriden by the later call to choosePrimaryShards in AnomalyDetectionIndices.
Testing done:
1. Manually verified newly created AD indices are all hidden.

Fix the bug that hidden index setting was overriden

---

.github/workflows/CI.yml
src/main/java/com/amazon/opendistroforelasticsearch/ad/AnomalyDetectorPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/ad/indices/AnomalyDetectionIndices.java

This is a forward-port of PR 394, 395.
Testing done:
1. Manually verified AD indices are hidden.

Change AD indices to be hidden indices instead of system indices

---

build.gradle

Signed-off-by: Tyler Ohlsen <ohltyler@amazon.com>
Bump gson dependency version.
Will track that [performance analyzer](https://github.com/opendistro-for-elasticsearch/performance-analyzer) performs a similar bump such that they are on the same version of gson.

Bump gson dependency version
